// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvehswcrxhdxztycnvgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2ZWhzd2NyeGhkeHp0eWNudmd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTA1MTMsImV4cCI6MjA2Mzk4NjUxM30.fQr6S_WCJwo86szintuzs0mjCa3ZIECF-JRFEr6DboE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);